import json
import sys

# HOW THE PROGRAM SHOULD BE CALLED
#
# You should have 1 files ready:
# 1.  The output file generated by the lexical analyzer.
#
# Call
# py syntactic.py <generated-output-file-name>

index = 0

def readToken(lexicalOutput):
    global index
    token = lexicalOutput["tokens"][index]["type"]
    index += 1
    return token

def parse(lexicalOutput):
    global index
    while index < len(lexicalOutput["tokens"]):
        token = readToken(lexicalOutput)
        if token == "OPERATION":
            if readToken(lexicalOutput) == "REGISTER":
                if readToken(lexicalOutput) != "REGISTER":
                    return False
            else:
                return False
        elif token == "ASSIGNMENT":
            token = readToken(lexicalOutput)
            if token == "REGISTER" or token == "INTEGER":
                if readToken(lexicalOutput) != "REGISTER":
                    return False
            else:
                return False
        elif index == (len(lexicalOutput["tokens"])) and token == "EOF":
            return True
        else:
            return False
    return False

def readLexicalOutput():
    with open(sys.argv[1]) as lexicalOutputFile:
        return json.load(lexicalOutputFile)

def main():
    lexicalOutput = readLexicalOutput()
    print(parse(lexicalOutput))

main()